services:
  php-cli:
    container_name: php-cli
    user: "1000:1000"
    build:
      context: .
      dockerfile: php-cli-local.dockerfile
    volumes:
      - type: bind
        source: .
        target: /var/www/html/
